### ISSUE TITLE
what's this about?

### ISSUE THREAD

**Issue by c-z-chen** [Turkyden/bit-coin#1]
ahh learning blockchain app development recently... so clicked in the first sec you created this repo.

but as no code is provided yet, I do not know what's this about... 'a chart of bitcoin', is, in my interpretation, a chart of bitcoin value growth? if it be so... then this isn't likely to be a dapp.

---

also are you interested in learning solidity together with me to do ethereum dapp development?

**Comment by turkyden** [comment]
Haha, it is just a demo. I am just  trying and learning blockchain.

**Comment by c-z-chen** [comment]
ah I see. lgtm!
